name: Android Inspector

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'snapo-desktop-compose/**'
      - '.github/workflows/android-inspector.yml'
      - 'VERSION'
  pull_request:
    branches:
      - main
      - master
    paths:
      - 'snapo-desktop-compose/**'
      - '.github/workflows/android-inspector.yml'
      - 'VERSION'

jobs:
  detekt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - name: Set up Java
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165
        with:
          distribution: temurin
          java-version: '17'
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@748248ddd2a24f49513d8f472f81c3a07d4d50e1
      - name: Grant execute permission for Gradle wrapper
        working-directory: snapo-desktop-compose
        run: chmod +x gradlew
      - name: Run Detekt
        working-directory: snapo-desktop-compose
        run: ./gradlew --no-daemon detekt
